%Recibe:
%   .Frecuencia de muestreo
%   .Frecuencia de corte inferior
%   .Frecuencia de paso inferior
%   .Frecuencia de paso superior
%   .Frecuencia de corte superior
%   .Atenuacion de la región inferior a la de paso (en dB)
%   .Magnitud de ripple (en dB)
%   .Atenuacion de la region superior a la de paso (en dB)

%Devuelve: objeto filtro

function filtro_pb = construir_filtro_pasabanda(fs, frec_corte_inferior, frec_paso_inferior, frec_paso_superior, frec_corte_superior, atenuacion_corte_inferior, ripple, atenuacion_corte_superior)
%FILTRO_400-500 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 09-Sep-2018 21:49:22

% Chebyshev Type II Bandpass filter designed using FDESIGN.BANDPASS.
% All frequency values are in Hz.

match = 'stopband';

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandpass(frec_corte_inferior, frec_paso_inferior, frec_paso_superior, frec_corte_superior, atenuacion_corte_inferior, ripple, atenuacion_corte_superior, fs);
filtro_pb = design(h, 'cheby2', 'MatchExactly', match);

% [EOF]
