s_db_3 = obtener_curva_de_decaimiento_en_db(h_3, fs);
s_db_6 = obtener_curva_de_decaimiento_en_db(h_6, fs);
s_db_12 = obtener_curva_de_decaimiento_en_db(h_12, fs);
s_db_15 = obtener_curva_de_decaimiento_en_db(h_15, fs);
s_db_30 = obtener_curva_de_decaimiento_en_db(h_30, fs);
t_s_3 = 0:1/fs:length(s_db_3)/fs - 1/fs;
t_s_6 = 0:1/fs:length(s_db_6)/fs - 1/fs;
t_s_12 = 0:1/fs:length(s_db_12)/fs - 1/fs;
t_s_15 = 0:1/fs:length(s_db_15)/fs - 1/fs;
t_s_30 = 0:1/fs:length(s_db_30)/fs - 1/fs;
figure;
plot(t_s_3, s_db_3);
figure;
plot(t_s_6, s_db_6);
figure;
plot(t_s_12, s_db_12);
figure;
plot(t_s_15, s_db_15);
figure;
plot(t_s_30, s_db_30);